/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.73
 * Generated at: 2018-05-10 11:36:07 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("    <head>\r\n");
      out.write("        <title>游戏后台</title>\r\n");
      out.write("        <meta charset=\"UTF-8\">\r\n");
      out.write("        <meta name=\"viewport\"  content=\"width=device-width,initial-scale=1.0\">\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"../bootstrap/css/bootstrap.min.css\">\r\n");
      out.write("    </head>\r\n");
      out.write("    <body>\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("    \t<div class=\"row\"></div>\r\n");
      out.write("\t    <form class=\"form-horizontal center-block\" action=\"/gm/login\" method=\"post\">\r\n");
      out.write("\t    \t<div class=\"form-group\">\r\n");
      out.write("\t    \t\t<label for=\"user\" class=\"col-sm-2 control-label\">用户</label>\r\n");
      out.write("\t    \t\t<div class=\"col-sm-4\">\r\n");
      out.write("\t    \t\t<input type=\"text\" id=\"user\" class=\"form-control\" name=\"user\" placeholder=\"输入用户名...\"/>\r\n");
      out.write("\t    \t\t</div>\r\n");
      out.write("\t    \t</div>\r\n");
      out.write("\t    \t<div class=\"form-group\">\r\n");
      out.write("\t    \t\t<label class=\"col-sm-2 control-label\">密码</label>\r\n");
      out.write("\t    \t\t<div class=\"col-sm-4\">\r\n");
      out.write("\t    \t\t\t<input type=\"password\" class=\"form-control\" name=\"password\" placeholder=\"输入密码...\"/>\r\n");
      out.write("\t    \t\t</div>\r\n");
      out.write("\t    \t</div>\r\n");
      out.write("\t    \t<div class=\"form-group\">\r\n");
      out.write("\t    \t\t<button type=\"submit\" class=\"btn btn-primary col-xs-offset-3\">登录</button>\r\n");
      out.write("\t    \t</div>\r\n");
      out.write("\t    </form>\r\n");
      out.write("    \t</div>\r\n");
      out.write("    </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
